spring:
  profiles:
    active:
    - dev
---
srping:
  profiles: dev   #开发环境
  aplication:
    name: microservicecloud-config-atguigu-dev
---
srping:
  profiles: test   #测试环境
  aplication:
    name: microservicecloud-config-atguigu-test
#请保存为UTF-8格式