spring:
  profiles:
    active:
    - dev
---
server:
  port: 8081
spring:
  profiles: dev
  appllication:
    name: cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http//127.0.0.1:7001/eureka
---
server:
  port: 8082
spring:
  profiles: test
  appllication:
    name: cloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http//127.0.0.1:7001/eureka